prefix foaf: <http://xmlns.com/foaf/0.1/> prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> prefix dbo: <http://dbpedia.org/ontology/>  SELECT DISTINCT * WHERE {   ?v1 rdf:type  <http://dbpedia.org/ontology/IceHockeyPlayer> .   ?v1 rdfs:label ?v2 .   ?v1 foaf:homepage ?v3 .   ?v1 dbo:birthPlace ?v4 .   ?v1 foaf:name ?v5 . } 
