prefix dbp: <http://dbpedia.org/property/>  prefix dbo: <http://dbpedia.org/ontology/>  SELECT DISTINCT * WHERE {    ?v1 dbp:author ?v2 .   ?v2 dbo:nationality ?v3 .   ?v3 <http://purl.org/dc/terms/subject> <http://dbpedia.org/resource/Category:American_people_of_Mexican_descent>  } 