prefix dbp: <http://dbpedia.org/property/>  prefix dbo: <http://dbpedia.org/ontology/>  SELECT DISTINCT * WHERE {    ?v1 dbp:author ?v2 .   ?v2 dbo:nationality ?v3 .   ?v3 <http://dbpedia.org/property/governmentType> <http://dbpedia.org/resource/Federal_republic>  } 